#include "MapDreamFlower.h"
#include "Banks/SetAutoBank.h"

BANKREF(map_dream_flower)

const Note map_dream_flower_notes[MAP_DREAM_FLOWER_NOTE_COUNT] = {
    {
        .type = TapLeft,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 148,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 226,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 291,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 337,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 430,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 539,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 603,
        .charge_frames = 90,
        .hold_frames = 120,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 834,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 928,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 1007,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 1114,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 32,
        .speed_modifier = 0,
        .appear_frame = 1209,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 1303,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 1411,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 27,
        .speed_modifier = 2,
        .appear_frame = 1505,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 1593,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 45,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 1695,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 125,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 34,
        .speed_modifier = 0,
        .appear_frame = 1734,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 1789,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 1889,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 1945,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 125,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 1985,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 45,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 2086,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 2180,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 29,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 1,
        .appear_frame = 2273,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 2320,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 2367,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 2431,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 2480,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 2574,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 2670,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 2715,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 36,
        .speed_modifier = 0,
        .appear_frame = 2763,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 2811,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 2,
        .appear_frame = 2859,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 2,
        .appear_frame = 2913,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 3007,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 97,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 3055,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 91,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 3148,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 31,
        .speed_modifier = 1,
        .appear_frame = 3260,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 129,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 3304,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 3397,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 32,
        .speed_modifier = 0,
        .appear_frame = 3521,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 3584,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 3677,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 3818,
        .charge_frames = 90,
        .hold_frames = 90,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 3970,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 4078,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 4219,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 4283,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 30,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 4360,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 4454,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 4596,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 2,
        .appear_frame = 4718,
        .charge_frames = 90,
        .hold_frames = 75,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 4817,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 4864,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 4943,
        .charge_frames = 90,
        .hold_frames = 35,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 35,
        .speed_modifier = 0,
        .appear_frame = 5018,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 65,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 5042,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 113,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 5090,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 75,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 5113,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 29,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 5135,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 5222,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 129,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 5323,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 1,
        .appear_frame = 5370,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 81,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 5420,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 36,
        .speed_modifier = 2,
        .appear_frame = 5469,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 5573,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 5621,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 60,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 5668,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 34,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 5714,
        .charge_frames = 90,
        .hold_frames = 28,
        .scanline_x = 126,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 5805,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 5906,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 110,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 6000,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 6055,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 6102,
        .charge_frames = 90,
        .hold_frames = 29,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 21,
        .speed_modifier = 1,
        .appear_frame = 6153,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 82,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 6205,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 30,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 6251,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 6347,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 6396,
        .charge_frames = 90,
        .hold_frames = 44,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 6520,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 6567,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 6631,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 6708,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 6785,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 6832,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 6896,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 6943,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 7022,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 7086,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 7211,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 7291,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 7353,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 7400,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 7478,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 7540,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 7648,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 21,
        .speed_modifier = 2,
        .appear_frame = 7787,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 7890,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 7938,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 16,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 8039,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 8080,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 8128,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 82,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 8182,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 8222,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 8247,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 8326,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 94,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 31,
        .speed_modifier = 1,
        .appear_frame = 8418,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 8466,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 8514,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 30,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 8560,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 8668,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 8811,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 8859,
        .charge_frames = 90,
        .hold_frames = 180,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 9102,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9150,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 9243,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9337,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 9448,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 9543,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 9638,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 9733,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 9782,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 9829,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9876,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 9924,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 10001,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 10094,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 16,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 10173,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 10220,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 10268,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 10410,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 10503,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 10598,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 10693,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 10786,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 10944,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 10975,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 11084,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 11179,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 11225,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 11350,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 11398,
        .charge_frames = 90,
        .hold_frames = 85,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 11546,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 11626,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 11674,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 11735,
        .charge_frames = 90,
        .hold_frames = 225,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 12057,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 12166,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 12306,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 12432,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 12527,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 12620,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 12730,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 12823,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 12963,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 13010,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 13118,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 2,
        .appear_frame = 13210,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 16,
        .speed_modifier = 1,
        .appear_frame = 13302,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
};
