#include "MapIsolation.h"
#include "Banks/SetAutoBank.h"

BANKREF(map_isolation)

const Note map_isolation_notes[MAP_ISOLATION_NOTE_COUNT] = {
    {
        .type = TapLeft,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 120,
        .charge_frames = 70,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 352,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 368,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 383,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 460,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 495,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 113,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 514,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 545,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 2,
        .speed_modifier = 0,
        .appear_frame = 561,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 639,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 639,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 687,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 34,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 32,
        .speed_modifier = 0,
        .appear_frame = 706,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 706,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 34,
        .speed_modifier = 0,
        .appear_frame = 769,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 786,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 65,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 2,
        .speed_modifier = 0,
        .appear_frame = 804,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 840,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 857,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 33,
        .speed_modifier = 0,
        .appear_frame = 875,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 911,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 2,
        .appear_frame = 928,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 65,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 1055,
        .charge_frames = 90,
        .hold_frames = 10,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 1074,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 1146,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 1164,
        .charge_frames = 70,
        .hold_frames = 50,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 1211,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 97,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 1221,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 1239,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 113,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 1302,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 125,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 1318,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 93,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 1334,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 61,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 33,
        .speed_modifier = 0,
        .appear_frame = 1350,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 29,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 1373,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 1388,
        .charge_frames = 50,
        .hold_frames = 17,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 1413,
        .charge_frames = 50,
        .hold_frames = 52,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 1433,
        .charge_frames = 90,
        .hold_frames = 25,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 1514,
        .charge_frames = 50,
        .hold_frames = 25,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 1514,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 1514,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 1548,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 129,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 1574,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 1590,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 45,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 1606,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 13,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 33,
        .speed_modifier = 0,
        .appear_frame = 1606,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 1621,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 1687,
        .charge_frames = 50,
        .hold_frames = 0,
        .scanline_x = 49,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 1693,
        .charge_frames = 60,
        .hold_frames = 0,
        .scanline_x = 81,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 1709,
        .charge_frames = 60,
        .hold_frames = 0,
        .scanline_x = 113,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 1740,
        .charge_frames = 60,
        .hold_frames = 0,
        .scanline_x = 109,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 1756,
        .charge_frames = 60,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 1787,
        .charge_frames = 70,
        .hold_frames = 0,
        .scanline_x = 125,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 1803,
        .charge_frames = 70,
        .hold_frames = 17,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
};
