#include "MapKomorebi.h"
#include "Banks/SetAutoBank.h"

BANKREF(map_komorebi)

const Note map_komorebi_notes[MAP_KOMOREBI_NOTE_COUNT] = {
    {
        .type = TapUp,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 38,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 148,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 258,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 368,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 463,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 589,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 699,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 809,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 919,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 1029,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 1153,
        .charge_frames = 90,
        .hold_frames = 75,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 1386,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 1496,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 1606,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 1684,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 1777,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 1916,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 1948,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 2058,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 2137,
        .charge_frames = 90,
        .hold_frames = 135,
        .scanline_x = 16,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 2367,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 2399,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 2509,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 2589,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 2729,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 2808,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 2838,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 2902,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 2950,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 3042,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 3074,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 3122,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 3184,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 3264,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 3406,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 3500,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 3532,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 3626,
        .charge_frames = 90,
        .hold_frames = 75,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 3749,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 3855,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 3965,
        .charge_frames = 90,
        .hold_frames = 120,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 4195,
        .charge_frames = 90,
        .hold_frames = 70,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 4313,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 4423,
        .charge_frames = 90,
        .hold_frames = 120,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 4653,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 4763,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 4873,
        .charge_frames = 90,
        .hold_frames = 120,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 5103,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 5213,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 126,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 5323,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 5449,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 5527,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 5605,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 5637,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 5761,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 5839,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 5887,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 5997,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 6107,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 33,
        .speed_modifier = 0,
        .appear_frame = 6233,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 6279,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 6435,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 6515,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 31,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 6579,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 6735,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 6905,
        .charge_frames = 90,
        .hold_frames = 120,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 7135,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 7183,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 7247,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 7293,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 7417,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 34,
        .speed_modifier = 0,
        .appear_frame = 7465,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 7529,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 7591,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 7639,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 7765,
        .charge_frames = 90,
        .hold_frames = 165,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 8040,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 8088,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 8198,
        .charge_frames = 90,
        .hold_frames = 60,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 8322,
        .charge_frames = 90,
        .hold_frames = 45,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 8493,
        .charge_frames = 90,
        .hold_frames = 105,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 8676,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 31,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 8770,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 8818,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 8944,
        .charge_frames = 90,
        .hold_frames = 105,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9175,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 9284,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 9364,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9504,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 9614,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 95,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 9724,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 9850,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 9960,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 63,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 10069,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 10117,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 10181,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 10291,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 10353,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 10413,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 10525,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 10635,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 95,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 10743,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 10775,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 10838,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
};
