#include "Banks/SetAutoBank.h"

#include "MapThirdboot.h"

BANKREF(map_thirdboot)

const Note map_thirdboot_notes[MAP_THIRDBOOT_NOTE_COUNT] = {
    {
        .type = TapLeft,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 84,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 100,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 116,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 134,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 150,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 212,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 228,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 244,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 262,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 278,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 323,
        .charge_frames = 90,
        .hold_frames = 40,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 380,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 396,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 412,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 430,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 446,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 491,
        .charge_frames = 90,
        .hold_frames = 35,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 543,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 559,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 575,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 593,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 608,
        .charge_frames = 90,
        .hold_frames = 75,
        .scanline_x = 111,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 730,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 778,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 809,
        .charge_frames = 90,
        .hold_frames = 40,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 882,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 898,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 30,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 35,
        .speed_modifier = 0,
        .appear_frame = 933,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 65,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 36,
        .speed_modifier = 0,
        .appear_frame = 947,
        .charge_frames = 90,
        .hold_frames = 25,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 39,
        .speed_modifier = 0,
        .appear_frame = 1021,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 1051,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 1082,
        .charge_frames = 90,
        .hold_frames = 50,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 1213,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 1247,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 1283,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 96,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 1361,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 30,
        .speed_modifier = 2,
        .appear_frame = 1361,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 1386,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 60,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 1424,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 16,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 1465,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 66,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 1512,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 124,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 1538,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 108,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 1562,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 60,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 1576,
        .charge_frames = 90,
        .hold_frames = 40,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 1673,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 82,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 1697,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 130,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 1726,
        .charge_frames = 90,
        .hold_frames = 50,
        .scanline_x = 96,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 34,
        .speed_modifier = 0,
        .appear_frame = 1801,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 0,
        .speed_modifier = 0,
        .appear_frame = 1833,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 18,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 1875,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 66,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 6,
        .speed_modifier = 1,
        .appear_frame = 1898,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 15,
        .speed_modifier = 0,
        .appear_frame = 1930,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 129,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 1965,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 2,
        .appear_frame = 1996,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 2060,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 35,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 2070,
        .charge_frames = 90,
        .hold_frames = 19,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 2176,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 125,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 2192,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 93,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 2215,
        .charge_frames = 90,
        .hold_frames = 40,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 2288,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 19,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 36,
        .speed_modifier = 0,
        .appear_frame = 2337,
        .charge_frames = 90,
        .hold_frames = 10,
        .scanline_x = 79,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 2357,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 99,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 2416,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 19,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 2464,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 115,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 2485,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 14,
        .speed_modifier = 0,
        .appear_frame = 2509,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 109,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 36,
        .speed_modifier = 1,
        .appear_frame = 2525,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 2576,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 2610,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 2,
        .speed_modifier = 0,
        .appear_frame = 2658,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 2658,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 2658,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 2658,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 34,
        .speed_modifier = 3,
        .appear_frame = 2658,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 2701,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 83,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 2743,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 75,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 25,
        .speed_modifier = 1,
        .appear_frame = 2780,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 36,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 26,
        .speed_modifier = 3,
        .appear_frame = 2792,
        .charge_frames = 90,
        .hold_frames = 22,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 29,
        .speed_modifier = 0,
        .appear_frame = 2831,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 99,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 5,
        .speed_modifier = 1,
        .appear_frame = 2862,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 92,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 2875,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 2921,
        .charge_frames = 90,
        .hold_frames = 30,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 2,
        .speed_modifier = 3,
        .appear_frame = 2968,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 3022,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 116,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 3069,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 27,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 20,
        .speed_modifier = 1,
        .appear_frame = 3106,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 84,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 38,
        .speed_modifier = 0,
        .appear_frame = 3134,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 112,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 3180,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 126,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 21,
        .speed_modifier = 0,
        .appear_frame = 3212,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 3227,
        .charge_frames = 90,
        .hold_frames = 25,
        .scanline_x = 79,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 18,
        .speed_modifier = 4,
        .appear_frame = 3284,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 3284,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 3349,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 133,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 3392,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 21,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 15,
        .speed_modifier = 1,
        .appear_frame = 3427,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 123,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 13,
        .speed_modifier = 3,
        .appear_frame = 3456,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 3468,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 130,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 25,
        .speed_modifier = 1,
        .appear_frame = 3510,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 28,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 3523,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 8,
        .speed_modifier = 0,
        .appear_frame = 3573,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 15,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 25,
        .speed_modifier = 3,
        .appear_frame = 3611,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 3633,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 99,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 3669,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 3713,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 75,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 10,
        .speed_modifier = 0,
        .appear_frame = 3754,
        .charge_frames = 90,
        .hold_frames = 26,
        .scanline_x = 48,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 36,
        .speed_modifier = 0,
        .appear_frame = 3792,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 84,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 3833,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 77,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 1,
        .speed_modifier = 1,
        .appear_frame = 3848,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 3917,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 3951,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 3967,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 4014,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 4014,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 31,
        .speed_modifier = 0,
        .appear_frame = 4091,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 127,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 30,
        .speed_modifier = 0,
        .appear_frame = 4108,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 110,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 4140,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 78,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 4172,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 34,
        .speed_modifier = 0,
        .appear_frame = 4172,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 4283,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 65,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 12,
        .speed_modifier = 0,
        .appear_frame = 4299,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 81,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 4346,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 23,
        .speed_modifier = 0,
        .appear_frame = 4346,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 128,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 4427,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 47,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 4444,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 20,
        .speed_modifier = 0,
        .appear_frame = 4480,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 80,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 4497,
        .charge_frames = 90,
        .hold_frames = 20,
        .scanline_x = 63,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 4597,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 17,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 4613,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 28,
        .speed_modifier = 0,
        .appear_frame = 4661,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 81,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 12,
        .speed_modifier = 2,
        .appear_frame = 4661,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 81,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 4740,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 45,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 9,
        .speed_modifier = 0,
        .appear_frame = 4779,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 4796,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 67,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 22,
        .speed_modifier = 0,
        .appear_frame = 4820,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 115,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 6,
        .speed_modifier = 0,
        .appear_frame = 4820,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 115,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 4921,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 5,
        .speed_modifier = 0,
        .appear_frame = 4954,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 99,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 7,
        .speed_modifier = 0,
        .appear_frame = 4968,
        .charge_frames = 90,
        .hold_frames = 82,
        .scanline_x = 127,
        .scanline_direction = 1,
    },
    {
        .type = Hold,
        .grid_idx = 38,
        .speed_modifier = 1,
        .appear_frame = 5073,
        .charge_frames = 90,
        .hold_frames = 25,
        .scanline_x = 111,
        .scanline_direction = -1,
    },
    {
        .type = TapRight,
        .grid_idx = 37,
        .speed_modifier = 0,
        .appear_frame = 5115,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapUp,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 5147,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 62,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 35,
        .speed_modifier = 0,
        .appear_frame = 5147,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 62,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 25,
        .speed_modifier = 0,
        .appear_frame = 5242,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 33,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 24,
        .speed_modifier = 0,
        .appear_frame = 5260,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 15,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 9,
        .speed_modifier = 2,
        .appear_frame = 5307,
        .charge_frames = 90,
        .hold_frames = 15,
        .scanline_x = 32,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 13,
        .speed_modifier = 0,
        .appear_frame = 5401,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 94,
        .scanline_direction = -1,
    },
    {
        .type = TapDown,
        .grid_idx = 26,
        .speed_modifier = 0,
        .appear_frame = 5425,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 46,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 1,
        .speed_modifier = 0,
        .appear_frame = 5465,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 34,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 18,
        .speed_modifier = 0,
        .appear_frame = 5568,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 44,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 4,
        .speed_modifier = 0,
        .appear_frame = 5587,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 82,
        .scanline_direction = 1,
    },
    {
        .type = Reverse,
        .grid_idx = 32,
        .speed_modifier = 0,
        .appear_frame = 5621,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = TapLeft,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 5725,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 62,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 17,
        .speed_modifier = 0,
        .appear_frame = 5740,
        .charge_frames = 90,
        .hold_frames = 40,
        .scanline_x = 32,
        .scanline_direction = -1,
    },
    {
        .type = Reverse,
        .grid_idx = 16,
        .speed_modifier = 0,
        .appear_frame = 5789,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 14,
        .scanline_direction = -1,
    },
    {
        .type = Hold,
        .grid_idx = 19,
        .speed_modifier = 0,
        .appear_frame = 5814,
        .charge_frames = 90,
        .hold_frames = 142,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapUp,
        .grid_idx = 3,
        .speed_modifier = 0,
        .appear_frame = 5886,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapLeft,
        .grid_idx = 11,
        .speed_modifier = 0,
        .appear_frame = 5911,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapDown,
        .grid_idx = 27,
        .speed_modifier = 0,
        .appear_frame = 5927,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
    {
        .type = TapRight,
        .grid_idx = 35,
        .speed_modifier = 0,
        .appear_frame = 5952,
        .charge_frames = 90,
        .hold_frames = 0,
        .scanline_x = 64,
        .scanline_direction = 1,
    },
};
