#include "Banks/SetAutoBank.h"
#include "GameAudio.h"
#include "GameData.h"
#include "Keys.h"
#include "Notes.h"
#include "Print.h"
#include "Scanline.h"
#include "Scroll.h"
#include "SpriteManager.h"
#include "Text.h"
#include "ZGBMain.h"

IMPORT_MAP(map_background);

IMPORT_TILES(mangrove_font_utility);

/** Represents the stored font offsets for all loaded game fonts. */
typedef struct {
    int8_t mangrove_font_utility_font_offset;
} FontOffset;

/** The saved game font offsets. */
static FontOffset font_offsets;

/** The current frame in the game. */
static uint16_t current_frame;

/** The index of the next note. */
static uint16_t next_note_idx;

/**
 * Display a note on the screen using Sprite Manager.
 *
 * @param note  The note to display.
 *
 * @return A pointer to the displayed sprite.
 */
static Sprite *DrawNote(const Note *note);

/**
 * Draw the performance indicator, healthbar, and health points.
 */
static void DrawHUD(void);

/**
 * Converts a string that contains numbers to characters that can be read and
 * displayed as healh bars.
 *
 * @param player_health Current player health as a string.
 *
 */
static char *HealthBar(char *player_health);

/** The total number of notes in the map. */
#define MAP_NOTE_COUNT 107

/** The array of notes in the map. */
static const Note map_notes[MAP_NOTE_COUNT] = {
    {.type = TapUp,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 22,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 112,
     .scanline_direction = 1},
    {.type = TapUp,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 132,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 62,
     .scanline_direction = -1},
    {.type = TapDown,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 243,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 49,
     .scanline_direction = 1},
    {.type = TapDown,
     .grid_idx = 23,
     .speed_modifier = 0,
     .appear_frame = 352,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 126,
     .scanline_direction = -1},
    {.type = TapDown,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 416,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 62,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 463,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 589,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 699,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 809,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 919,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 1029,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 1153,
     .charge_frames = 90,
     .hold_frames = 75,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 30,
     .speed_modifier = 0,
     .appear_frame = 1386,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 11,
     .speed_modifier = 0,
     .appear_frame = 1496,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 6,
     .speed_modifier = 0,
     .appear_frame = 1606,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 37,
     .speed_modifier = 0,
     .appear_frame = 1684,
     .charge_frames = 90,
     .hold_frames = 45,
     .scanline_x = 95,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 1777,
     .charge_frames = 90,
     .hold_frames = 45,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 26,
     .speed_modifier = 0,
     .appear_frame = 1916,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 12,
     .speed_modifier = 0,
     .appear_frame = 1948,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = 1},
    {.type = TapUp,
     .grid_idx = 13,
     .speed_modifier = 0,
     .appear_frame = 2058,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 2137,
     .charge_frames = 90,
     .hold_frames = 135,
     .scanline_x = 16,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 2367,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 2399,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 23,
     .speed_modifier = 0,
     .appear_frame = 2509,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 2589,
     .charge_frames = 90,
     .hold_frames = 45,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 2729,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 48,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 39,
     .speed_modifier = 0,
     .appear_frame = 2808,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 7,
     .speed_modifier = 0,
     .appear_frame = 2838,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 2902,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 2950,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 14,
     .speed_modifier = 0,
     .appear_frame = 3042,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 28,
     .speed_modifier = 0,
     .appear_frame = 3074,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 25,
     .speed_modifier = 0,
     .appear_frame = 3122,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 31,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 9,
     .speed_modifier = 0,
     .appear_frame = 3184,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 3264,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 17,
     .speed_modifier = 0,
     .appear_frame = 3406,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 3500,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 23,
     .speed_modifier = 0,
     .appear_frame = 3532,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 3626,
     .charge_frames = 90,
     .hold_frames = 75,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 24,
     .speed_modifier = 0,
     .appear_frame = 3749,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 9,
     .speed_modifier = 0,
     .appear_frame = 3855,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 3965,
     .charge_frames = 90,
     .hold_frames = 120,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 4195,
     .charge_frames = 90,
     .hold_frames = 70,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 4313,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 4423,
     .charge_frames = 90,
     .hold_frames = 120,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 4653,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 4763,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 4873,
     .charge_frames = 90,
     .hold_frames = 120,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 1,
     .speed_modifier = 0,
     .appear_frame = 5103,
     .charge_frames = 90,
     .hold_frames = 15,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 39,
     .speed_modifier = 0,
     .appear_frame = 5213,
     .charge_frames = 90,
     .hold_frames = 15,
     .scanline_x = 126,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 11,
     .speed_modifier = 0,
     .appear_frame = 5323,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 27,
     .speed_modifier = 0,
     .appear_frame = 5449,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 5527,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 15,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 5605,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 5637,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 5761,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 5839,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 5887,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 5997,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = TapRight,
     .grid_idx = 23,
     .speed_modifier = 0,
     .appear_frame = 6107,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 33,
     .speed_modifier = 0,
     .appear_frame = 6233,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 31,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 0,
     .speed_modifier = 0,
     .appear_frame = 6279,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 15,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 6435,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 17,
     .speed_modifier = 0,
     .appear_frame = 6515,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 31,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 21,
     .speed_modifier = 0,
     .appear_frame = 6579,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 3,
     .speed_modifier = 0,
     .appear_frame = 6735,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 26,
     .speed_modifier = 0,
     .appear_frame = 6905,
     .charge_frames = 90,
     .hold_frames = 120,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 15,
     .speed_modifier = 0,
     .appear_frame = 7135,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 7183,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 24,
     .speed_modifier = 0,
     .appear_frame = 7247,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 17,
     .speed_modifier = 0,
     .appear_frame = 7293,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 5,
     .speed_modifier = 0,
     .appear_frame = 7417,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 34,
     .speed_modifier = 0,
     .appear_frame = 7465,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 7529,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 30,
     .speed_modifier = 0,
     .appear_frame = 7591,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 11,
     .speed_modifier = 0,
     .appear_frame = 7639,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 19,
     .speed_modifier = 0,
     .appear_frame = 7765,
     .charge_frames = 90,
     .hold_frames = 165,
     .scanline_x = 63,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 8040,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 3,
     .speed_modifier = 0,
     .appear_frame = 8088,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 63,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 8198,
     .charge_frames = 90,
     .hold_frames = 60,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 38,
     .speed_modifier = 0,
     .appear_frame = 8322,
     .charge_frames = 90,
     .hold_frames = 45,
     .scanline_x = 111,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 8493,
     .charge_frames = 90,
     .hold_frames = 105,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 1,
     .speed_modifier = 0,
     .appear_frame = 8676,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 31,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 13,
     .speed_modifier = 0,
     .appear_frame = 8770,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 10,
     .speed_modifier = 0,
     .appear_frame = 8818,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 8944,
     .charge_frames = 90,
     .hold_frames = 105,
     .scanline_x = 79,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 9175,
     .charge_frames = 90,
     .hold_frames = 15,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = TapRight,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 9284,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 29,
     .speed_modifier = 0,
     .appear_frame = 9364,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Reverse,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 9504,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 13,
     .speed_modifier = 0,
     .appear_frame = 9614,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 95,
     .scanline_direction = -1},
    {.type = TapLeft,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 9724,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = Reverse,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 9850,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 27,
     .speed_modifier = 0,
     .appear_frame = 9960,
     .charge_frames = 90,
     .hold_frames = 15,
     .scanline_x = 63,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 7,
     .speed_modifier = 0,
     .appear_frame = 10069,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = -1},
    {.type = TapDown,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 10117,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 24,
     .speed_modifier = 0,
     .appear_frame = 10181,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 29,
     .speed_modifier = 0,
     .appear_frame = 10291,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = Hold,
     .grid_idx = 23,
     .speed_modifier = 0,
     .appear_frame = 10353,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 127,
     .scanline_direction = 1},
    {.type = TapLeft,
     .grid_idx = 15,
     .speed_modifier = 0,
     .appear_frame = 10413,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 127,
     .scanline_direction = -1},
    {.type = TapDown,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 10525,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
    {.type = Hold,
     .grid_idx = 37,
     .speed_modifier = 0,
     .appear_frame = 10635,
     .charge_frames = 90,
     .hold_frames = 30,
     .scanline_x = 95,
     .scanline_direction = 1},
    {.type = TapUp,
     .grid_idx = 22,
     .speed_modifier = 0,
     .appear_frame = 10743,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 111,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 20,
     .speed_modifier = 0,
     .appear_frame = 10775,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 79,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 18,
     .speed_modifier = 0,
     .appear_frame = 10807,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 47,
     .scanline_direction = -1},
    {.type = TapUp,
     .grid_idx = 16,
     .speed_modifier = 0,
     .appear_frame = 10839,
     .charge_frames = 90,
     .hold_frames = 0,
     .scanline_x = 15,
     .scanline_direction = -1},
};

void START(void) {
    DISABLE_SPRITE_FLICKERING; // ... otherwise it looks glitchy

    current_frame = 0;
    next_note_idx = 0;

    InitGameAudio(); // custom init

    InitScroll(BANK(map_background), &map_background, 0, 0);

    INIT_FONT(mangrove_font_utility, PRINT_BKG);
    font_offsets.mangrove_font_utility_font_offset = font_offset;

    SpriteManagerAdd(SpriteScanline, SCANLINE_START_X, SCANLINE_START_Y);

    PlayCurrentMapSong();
}

void UPDATE(void) {
    TickGameAudio(); // tick manually here because CrossZGB's audio ticking is
                     // faster than and independent of VBL updates
    ++current_frame;

    while (next_note_idx < MAP_NOTE_COUNT) {
        Note current_note = map_notes[next_note_idx];

        if (current_frame < current_note.appear_frame)
            break;

        DrawNote(&current_note);

        ++next_note_idx;
    }

    DrawHUD();
    // NOTE: This might be too obscure/hidden for the average user to figure
    // out.
    // TODO: Try to make a small indicator for this.
    if (KEY_PRESSED(J_SELECT) && KEY_PRESSED(J_START))
        SetState(StateMenu);
}

static Sprite *DrawNote(const Note *note) {
    // get row/col
    uint8_t grid_row = note->grid_idx / GRID_COLS;
    uint8_t grid_col = note->grid_idx % GRID_COLS;

    // get xy
    uint8_t pixel_x = GRID_START_X + NOTE_WIDTH * grid_col;
    uint8_t pixel_y = GRID_START_Y + NOTE_HEIGHT * grid_row;

    uint8_t note_sprite_type;
    switch (note->type) {
    case TapLeft:
    case TapRight:
        note_sprite_type = SpriteTapNoteHorizontal;
        break;
    case TapUp:
    case TapDown:
        note_sprite_type = SpriteTapNoteVertical;
        break;
    case Reverse:
        note_sprite_type = SpriteReverseNote;
        break;
    case Hold:
        note_sprite_type = SpriteHoldNote;
        break;
    default:
        return NULL; // TODO: implement other notes
    }

    Sprite *note_sprite = SpriteManagerAdd(note_sprite_type, pixel_x, pixel_y);
    if (!note_sprite)
        return NULL;

    // flip if needed
    if (note->type == TapLeft)
        note_sprite->mirror = V_MIRROR;
    else if (note->type == TapDown)
        note_sprite->mirror = H_MIRROR;

    // set charge frames
    switch (note->type) {
    case TapLeft:
    case TapRight:
    case TapUp:
    case TapDown: {
        TapNoteData *note_data = (TapNoteData *)note_sprite->custom_data;
        note_data->speed_modifier = note->speed_modifier;
        note_data->charge_frames = note->charge_frames;
        note_data->scanline_x = note->scanline_x;
        note_data->scanline_direction = note->scanline_direction;
        break;
    }
    case Reverse: {
        ReverseNoteData *note_data =
            (ReverseNoteData *)note_sprite->custom_data;
        note_data->speed_modifier = note->speed_modifier;
        note_data->charge_frames = note->charge_frames;
        note_data->scanline_x = note->scanline_x;
        note_data->scanline_direction = note->scanline_direction;
        break;
    }
    case Hold: {
        HoldNoteData *note_data = (HoldNoteData *)note_sprite->custom_data;
        note_data->speed_modifier = note->speed_modifier;
        note_data->charge_frames = note->charge_frames;
        note_data->hold_frames = note->hold_frames;
        note_data->scanline_x = note->scanline_x;
        note_data->scanline_direction = note->scanline_direction;
        break;
    }
    }

    return note_sprite;
}

static void DrawHUD(void) {
    wait_vbl_done();

    font_offset = font_offsets.mangrove_font_utility_font_offset;

    DrawText("PERFECT", 1, 16, TEXT_ANCHOR_LEFT, 0, TEXT_UTILITY_PALETTE_IDX);
    DrawText(HealthBar("66662"), 9, 16, TEXT_ANCHOR_LEFT, 0,
             TEXT_UTILITY_PALETTE_IDX);
    DrawText("1000", 15, 16, TEXT_ANCHOR_LEFT, 0, TEXT_UTILITY_PALETTE_IDX);
}

static char *HealthBar(char *player_health) {

    static char translated_string[6] = "     ";
    char translator[] = "!'()-.:";
    for (uint8_t i = 0; i < strlen(player_health); ++i) {
        translated_string[i] =
            translator[player_health[i] - '0']; // Converts string value to
                                                // literal numerical value.
    }
    return translated_string;
}
